package com.abu.dal.entity;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * 对应表: mbr_member_phone_open_id_ref
 *
 * @author
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
public class MbrMemberPhoneOpenIdRefDO extends MbrMemberPhoneOpenIdRefDOKey {
    /**
     * 字段: phone 会员手机号
     */
    private String phone;

    /**
     * 字段: memberId 会员编号
     */
    private String memberId;

    /**
     * 字段: memberCardNo 会员卡号
     */
    private String memberCardNo;

    /**
     * 字段: openId 用户在注册来源公众号下的open id
     */
    private String openId;

    /**
     * 字段: appId openId 归属的公众号app id
     */
    private String appId;

    /**
     * 字段: gmtCreate 新增记录时间
     */
    private Date gmtCreate;

    /**
     * 字段: gmtModified 更新记录时间
     */
    private Date gmtModified;
}